apiVersion: v1
kind: Namespace
metadata:
  name: sdfsdffsd-dev
  labels:
    environment-id: env_b97f0cbd-d048-4b44-9cc6-9e196184da26
    project-id: project_ce2db796-a17b-4482-9401-65f15bda7a88
    project-name: sdfsdffsd
    environment-name: dev
    organization-id: org_148c18cf-e442-4aa8-ace9-b84a9946c8be
